apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: python-kss-ingress
spec:
  rules:
    - host: python-kss.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: python-kss
                port:
                  number: 5000
