name: CI/CD Pipeline

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest  

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
    
    - name: Run tests
      run: |
        # Run any tests you may have (or just skip if you have none)
        pytest || echo "No tests found, skipping"

  docker-build:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # - name: Login to Docker Hub
    #   run: |
    #     docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build & Push image
      run: |
        # docker build -t plminha13/python-kss:latest .
        # docker push plminha13/python-kss:latest

        docker build -t plminha13/python-kss:${{ github.sha }} .
        docker tag plminha13/python-kss:${{ github.sha }} plminha13/python-kss:latest
        docker push plminha13/python-kss:${{ github.sha }}
        docker push plminha13/python-kss:latest

    # - name: Deploy to Minikube
    #   run: |
    #     kubectl apply -f kubernetes/
    #     kubectl rollout restart deployment python-flask-app

    # - name: Checkout repository
    #   uses: actions/checkout@v2

    # - name: Set up Docker Buildx
    #   uses: docker/setup-buildx-action@v2

    # - name: Cache Docker layers
    #   uses: actions/cache@v2
    #   with:
    #     path: /tmp/.buildx-cache
    #     key: ${{ runner.os }}-buildx-${{ github.sha }}
    #     restore-keys: |
    #       ${{ runner.os }}-buildx-
    
    # - name: Build and push Docker image
    #   uses: docker/build-push-action@v2
    #   with:
    #     context: .
    #     push: true
    #     tags: yourdockerhubusername/python-flask-app:latest
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASSWORD }}
    
  deploy:
    needs: docker-build
    # runs-on: self-hosted
    runs-on: [self-hosted, Linux, X64]

    steps:
    - uses: actions/checkout@v4
    # - name: Set up Kubernetes credentials
    #   uses: azure/setup-kubeconfig@v1
    #   with:
    #     kubeconfig: ${{ secrets.KUBE_CONFIG }}

    # - name: Deploy to Kubernetes
    #   run: |
    #     kubectl apply -f kubernetes/deployment.yaml
    #     kubectl apply -f kubernetes/service.yaml

    # Docker desktop
    # - name: Use Docker Desktop context
    #   shell: bash
    #   run: |
    #     kubectl config use-context docker-desktop

    - name: Set up K3s Kubeconfig
      run: |
        echo "${{ secrets.K3S_KUBECONFIG }}" > ~/.kube/config
        kubectl config use-context default

    - name: Wait for Kubernetes API
      shell: bash
      run: |
        echo "Waiting for Kubernetes API..."
        for i in {1..20}; do
          if kubectl get nodes; then
            echo "Kubernetes API is ready"
            break
          fi
          echo "Kubernetes not ready yet, retrying..."
          sleep 5
        done

    # Deploy with Docker desktop
    # - name: Deploy to Kubernetes
    #   shell: bash
    #   run: |
    #     # kubectl config use-context docker-desktop
    #     # kubectl apply -f k8s/deployment.yaml
    #     # kubectl apply -f k8s/service.yaml

    #     # kubectl config use-context docker-desktop
    #     # kubectl set image deployment/python-kss \
    #     #   python-app=plminha13/python-kss:${{ github.sha }} || true
    #     # kubectl apply -f k8s/deployment.yaml
    #     # kubectl apply -f k8s/service.yaml

    #     set -e
    #     # kubectl config use-context docker-desktop

    #     echo "Apply manifests"
    #     kubectl apply -f k8s/deployment.yaml
    #     kubectl apply -f k8s/service.yaml
    #     kubectl apply -f k8s/ingress.yaml

    #     echo "Update image"
    #     kubectl set image deployment/python-kss \
    #       python-kss=plminha13/python-kss:${{ github.sha }}

    - name: Deploy to K3s Kubernetes
      run: |
        set -e
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
        kubectl apply -f k8s/ingress.yaml

        kubectl patch svc python-kss -p '{"spec":{"type":"NodePort","ports":[{"port":5000,"targetPort":5000,"nodePort":31102}]}}'

        kubectl set image deployment/python-kss \
          python-kss=plminha13/python-kss:${{ github.sha }}

    - name: Verify rollout
      shell: bash
      # run: kubectl rollout status deployment/python-kss
      run: |
        kubectl rollout status deployment/python-kss --timeout=120s

    # - name: Print access URL
    #   run: |
    #     echo "Your Python app is now accessible at: http://127.0.0.1:31102"

    - name: Expose app on localhost
      run: |
        nohup kubectl port-forward svc/python-kss 5000:5000 > /tmp/port-forward.log 2>&1 &
        sleep 3
        echo "App available at http://localhost:5000"
